# Generated by Django 5.2.4 on 2025-08-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes_app', '0002_searchquery_searchsuggestion'),
    ]

    operations = [
    ]
