# Generated by Django 5.2.4 on 2025-08-14 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes_app', '0003_auto_20250813_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='scene_images/originals/')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='scene_images/large/')),
                ('medium_image', models.ImageField(blank=True, null=True, upload_to='scene_images/medium/')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='scene_images/small/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='scene_images/thumbnails/')),
                ('caption', models.CharField(blank=True, help_text='Image caption or title', max_length=500)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of image in gallery')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for the scene')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Original file size in bytes')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(blank=True, help_text='Image format (JPEG, PNG, etc.)', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='scenes_app.scene')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['scene', 'order'], name='scenes_app__scene_i_938d90_idx'), models.Index(fields=['scene', 'is_primary'], name='scenes_app__scene_i_b4bfcf_idx'), models.Index(fields=['uploaded_at'], name='scenes_app__uploade_b4150a_idx')],
            },
        ),
    ]
